CREATE OR REPLACE TASK TS_HOURLY_FRAUD_SCORING
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '60 MINUTE'
AS
    INSERT INTO FINANCIAL_ANALYTICS.FRAUD_DETECTION.FRAUD_SCORES (
        ACCOUNT_ID, 
        TRANSACTION_TS, 
        AMOUNT, 
        ANOMALY_SCORE, 
        IS_ANOMALY
    )
    SELECT
        fv.ACCOUNT_ID, 
        fv.TRANSACTION_TS, 
        fv.AMOUNT,
        FINANCIAL_ANALYTICS.FRAUD_DETECTION.SCORE_TRANSACTION(
            fv.AMOUNT, 
            fv.AMT_1HR_ACCT, 
            fv.COUNT_24HR_ACCT, 
            fv.HOUR_OF_DAY, 
            fv.NEW_MERCHANT_COUNT_7D, 
            fv.AMT_Z_SCORE_30D, 
            fv.CARD_PRESENT_RATIO_7D
        ) AS ANOMALY_SCORE,
        ANOMALY_SCORE < -0.04 -- <<< NEW, TIGHTER THRESHOLD
    FROM
        FINANCIAL_ANALYTICS.FRAUD_DETECTION.V_MODEL_FEATURES fv
    LEFT JOIN FINANCIAL_ANALYTICS.FRAUD_DETECTION.FRAUD_SCORES fs 
        ON fv.TRANSACTION_TS = fs.TRANSACTION_TS AND fv.ACCOUNT_ID = fs.ACCOUNT_ID
    WHERE fs.TRANSACTION_TS IS NULL
    AND fv.AMT_Z_SCORE_30D IS NOT NULL;

-- Keep the task active
ALTER TASK TS_HOURLY_FRAUD_SCORING RESUME;

EXECUTE TASK TS_HOURLY_FRAUD_SCORING;
SELECT
    COUNT(*) AS NEW_HIGH_RISK_ALERT_COUNT,
    MIN(ANOMALY_SCORE) AS LOWEST_SCORE_FOUND
FROM FINANCIAL_ANALYTICS.FRAUD_DETECTION.FRAUD_SCORES
WHERE ANOMALY_SCORE < -0.05;

