-- 1. Create the database (if it doesn't exist)
CREATE DATABASE IF NOT EXISTS FINANCIAL_ANALYTICS;

-- 2. Create the schema (if it doesn't exist)
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION;

-- 3. ***THIS IS THE COMMAND THAT FIXES THE ERROR***
-- It tells the current session where to put the tables and views.
USE SCHEMA FINANCIAL_ANALYTICS.FRAUD_DETECTION;

-- 4. Now, run your CREATE TABLE command
CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
    ACCOUNT_ID VARCHAR,
    TRANSACTION_TS TIMESTAMP_NTZ, 
    AMOUNT DECIMAL(10, 2),
    -- ... rest of your columns
    MERCHANT_CATEGORY_CODE VARCHAR,
    POS_ENTRY_MODE VARCHAR,
    POS_CONDITION_CODE VARCHAR
);

-- 5. And create the stage
CREATE OR REPLACE STAGE RAW_DATA_STAGE COMMENT = 'Internal stage for CSV data ingestion.';

USE SCHEMA FINANCIAL_ANALYTICS.FRAUD_DETECTION;


ALTER TABLE RAW_TRANSACTIONS ADD COLUMN CARD_PRESENT BOOLEAN;
ALTER TABLE RAW_TRANSACTIONS ADD COLUMN MERCHANTNAME VARCHAR;

USE SCHEMA FINANCIAL_ANALYTICS.FRAUD_DETECTION;
SELECT COUNT(*) FROM V_MODEL_FEATURES LIMIT 1;