USE SCHEMA FINANCIAL_ANALYTICS.FRAUD_DETECTION;
CREATE OR REPLACE TABLE FRAUD_SCORES (
    ACCOUNT_ID VARCHAR,
    TRANSACTION_TS TIMESTAMP_NTZ,
    AMOUNT DECIMAL(10, 2),
    ANOMALY_SCORE FLOAT,
    IS_ANOMALY BOOLEAN
);
