CREATE OR REPLACE VIEW FINANCIAL_ANALYTICS.FRAUD_DETECTION.V_FRAUD_REPORTING_VIEW AS
SELECT
    t.TRANSACTION_TS,
    t.ACCOUNT_ID,
    t.AMOUNT,
    t.MERCHANTNAME,
    t.CARD_PRESENT,
    s.ANOMALY_SCORE,
    s.IS_ANOMALY,
    CASE 
        WHEN s.ANOMALY_SCORE < -0.06 THEN 'High Risk (Alert)'       -- The 11 transactions you isolated
        WHEN s.ANOMALY_SCORE BETWEEN -0.06 AND -0.05 THEN 'Medium Risk (Monitor)' -- Scores that were close to the old cutoff
        ELSE 'Low Risk'
    END AS RISK_LEVEL -- The key classification field for Tableau
FROM
    FINANCIAL_ANALYTICS.FRAUD_DETECTION.FRAUD_SCORES s
JOIN
    FINANCIAL_ANALYTICS.FRAUD_DETECTION.RAW_TRANSACTIONS t
    ON s.TRANSACTION_TS = t.TRANSACTION_TS AND s.ACCOUNT_ID = t.ACCOUNT_ID
ORDER BY s.ANOMALY_SCORE ASC;

select * 
from FINANCIAL_ANALYTICS.FRAUD_DETECTION.V_FRAUD_REPORTING_VIEW;